site_name: Gillian Florence - Technical Writer
site_url: https://github.com/gillian-florence/portfolio
theme:
  name: material
  palette:
      # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
      text: Roboto
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Writing Samples:
    - Administrator Guide: 
      - About This Sample: admin-guide/index.md
      - Install & Configure: admin-guide/installation.md 
      - Features:
        - Working Alone Timer: 
          - Overview: admin-guide/wat-overview.md
          - Metadata: admin-guide/wat-metadata.md
          - Configuration: 
            - Configuration Overview: admin-guide/wat-configuration.md
            - Set Up Service Resources and Service Territories: admin-guide/wat-config-setup-service-resource.md
        - Union Rules: 
          - Overview: admin-guide/unionrules-overview.md
          - Metadata: 
            - Custom Objects: admin-guide/unionrules-metadata-customobjects.md
          - Configuration: admin-guide/unionrules-configuration.md
        - Mass Recurring Non-Availabilties: 
          - Overview: admin-guide/massrecurring-overview.md
          - Metadata: admin-guide/massrecurring-metadata.md
    - User Guide:
      - Overview (PDF Sample): user-guide/index.md
  - Published Blogs: published-blogs.md
  - About Me: 
    - Overview: about-me.md
    - Athletic Background: athletic-honours.md
  - Help Centre (Coming Soon): knowledge-base.md


     
  
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.magiclink:
      hide_protocol: false
      normalize_issue_symbols: false
      user: 
      provider: github
      repo: 
      repo_url_shorthand: true
      repo_url_shortener: false
      social_url_shorthand: false
      social_url_shortener: false
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.snippets:
      check_paths: true
      url_download: false
      url_max_size: 33554432
      url_timeout: 10
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/gillianflorence"
      name: "Connect with me on LinkedIn"
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gillian-florence/mkdocs-material-project


copyright: |
  
  &copy; 2025 <a href="https://github.com/gillian-florence/mkdocs-material-project"  target="_blank" rel="noopener">Gillian Florence</a>
